version: "3.9"

services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox
    ports:
      - "50021:50021"
    networks:
      - secretary-net

networks:
  secretary-net:
    external: true
